platform :ios, '12.1'

target 'BeckonExample' do
    use_frameworks!

    pod 'Beckon', :path => '.'
end

target 'Beckon' do
    use_frameworks!

    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'RxFeedback'
end
